# Generated by Django 4.2 on 2025-12-25
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('cards_added', models.PositiveIntegerField(default=0)),
                ('cards_updated', models.PositiveIntegerField(default=0)),
                ('raw_content', models.TextField(blank=True, help_text='Original import file content')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Collection Import',
                'verbose_name_plural': 'Collection Imports',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Number of regular copies owned')),
                ('premium_quantity', models.PositiveIntegerField(default=0, help_text='Number of premium (foil) copies owned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(help_text='The card in the collection', on_delete=django.db.models.deletion.CASCADE, related_name='collection_entries', to='cards.card')),
            ],
            options={
                'verbose_name': 'Collection Entry',
                'verbose_name_plural': 'Collection Entries',
                'ordering': ['card__card_set', 'card__eternal_id'],
                'unique_together': {('card',)},
            },
        ),
    ]
