# Generated by Django 4.2.26 on 2025-11-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Deck name', max_length=200)),
                ('format', models.CharField(choices=[('Throne', 'Throne'), ('Expedition', 'Expedition')], default='Throne', help_text='Game format (Throne or Expedition)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Deck description or notes')),
                ('archetype', models.CharField(blank=True, help_text='Primary archetype (Aggro, Midrange, Control, Combo)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeckTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('color', models.CharField(default='gray', help_text="Tailwind color class (e.g., 'red', 'blue', 'green')", max_length=20)),
                ('description', models.CharField(blank=True, help_text='Tag description', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeckVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Version number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, help_text='Notes about what changed in this version', max_length=500)),
                ('deck', models.ForeignKey(help_text='The deck this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='decks.deck')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('deck', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DeckVersionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of copies in this slot')),
                ('is_market', models.BooleanField(default=False, help_text='True if this card is in the market')),
                ('card', models.ForeignKey(help_text='The card in this version', on_delete=django.db.models.deletion.CASCADE, related_name='version_entries', to='cards.card')),
                ('deck_version', models.ForeignKey(help_text='The deck version containing this card', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deckversion')),
            ],
            options={
                'ordering': ['is_market', 'card__cost', 'card__name'],
            },
        ),
        migrations.CreateModel(
            name='DeckMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_archetype', models.CharField(blank=True, help_text="Opponent archetype name (e.g., 'Aggro', 'FJS Midrange')", max_length=100)),
                ('assessment', models.CharField(choices=[('favorable', 'Favorable'), ('even', 'Even'), ('unfavorable', 'Unfavorable'), ('unknown', 'Unknown')], default='unknown', help_text='How favorable is this matchup', max_length=20)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Strategy notes for this matchup')),
                ('key_cards', models.CharField(blank=True, help_text='Important cards in this matchup (comma-separated)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(help_text='The deck this matchup is recorded for', on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='decks.deck')),
                ('opponent_deck', models.ForeignKey(blank=True, help_text='Specific opponent deck (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchups_against', to='decks.deck')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags/archetypes for this deck', related_name='decks', to='decks.decktag'),
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of copies in this slot')),
                ('is_market', models.BooleanField(default=False, help_text='True if this card is in the market, False if main deck')),
                ('card', models.ForeignKey(help_text='The card in the deck', on_delete=django.db.models.deletion.CASCADE, related_name='deck_entries', to='cards.card')),
                ('deck', models.ForeignKey(help_text='The deck containing this card', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck')),
            ],
            options={
                'ordering': ['is_market', 'card__cost', 'card__name'],
                'unique_together': {('deck', 'card', 'is_market')},
            },
        ),
    ]
