# Generated by Django 4.2.26 on 2025-11-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Set number (e.g., 1 for Set1)', unique=True)),
                ('name', models.CharField(blank=True, help_text="Set name (e.g., 'The Empty Throne')", max_length=100)),
            ],
            options={
                'verbose_name': 'Card Set',
                'verbose_name_plural': 'Card Sets',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eternal_id', models.IntegerField(help_text="Eternal's internal card ID")),
                ('name', models.CharField(help_text='Card name', max_length=200)),
                ('card_text', models.TextField(blank=True, help_text='Card rules text')),
                ('card_type', models.CharField(choices=[('Unit', 'Unit'), ('Spell', 'Spell'), ('Fast Spell', 'Fast Spell'), ('Attachment', 'Attachment'), ('Weapon', 'Weapon'), ('Relic', 'Relic'), ('Relic Weapon', 'Relic Weapon'), ('Curse', 'Curse'), ('Power', 'Power'), ('Sigil', 'Sigil'), ('Site', 'Site'), ('Curse Weapon', 'Curse Weapon')], help_text='Primary card type', max_length=50)),
                ('unit_types', models.JSONField(blank=True, default=list, help_text="Unit subtypes as a list (e.g., ['Gunslinger', 'Rebel'])")),
                ('cost', models.IntegerField(default=0, help_text='Power cost')),
                ('influence', models.CharField(blank=True, help_text="Influence requirement string (e.g., '{F}{F}')", max_length=50)),
                ('attack', models.IntegerField(default=0, help_text='Attack value (units/weapons)')),
                ('health', models.IntegerField(default=0, help_text='Health value (units) or armor (weapons)')),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Legendary', 'Legendary'), ('Promo', 'Promo'), ('Basic', 'Basic'), ('None', 'None')], default='Common', help_text='Card rarity', max_length=20)),
                ('deck_buildable', models.BooleanField(default=True, help_text='Whether this card can be added to constructed decks')),
                ('image_url', models.URLField(blank=True, help_text='URL to card image on EternalWarcry', max_length=500)),
                ('details_url', models.URLField(blank=True, help_text='URL to card details page on EternalWarcry', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_set', models.ForeignKey(help_text='The expansion set this card belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.cardset')),
            ],
            options={
                'ordering': ['card_set', 'eternal_id'],
                'indexes': [models.Index(fields=['name'], name='cards_card_name_a125cc_idx'), models.Index(fields=['card_type'], name='cards_card_card_ty_f28ef4_idx'), models.Index(fields=['rarity'], name='cards_card_rarity_0cc733_idx'), models.Index(fields=['cost'], name='cards_card_cost_441ca8_idx'), models.Index(fields=['deck_buildable'], name='cards_card_deck_bu_81272e_idx')],
                'unique_together': {('card_set', 'eternal_id')},
            },
        ),
    ]
